// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayboxCache;

#nullable disable

namespace SqlDisCache.Infrastrukture.Migrations
{
    [DbContext(typeof(DistributedCacheContext))]
    partial class DistributedCacheContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CacheTagTestCache", b =>
                {
                    b.Property<string>("CachItemsId")
                        .HasColumnType("nvarchar(449)");

                    b.Property<string>("TagsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CachItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("CacheTagTestCache");
                });

            modelBuilder.Entity("SqlDisCache.Infrastrukture.Entity.CacheTag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("CacheTag");
                });

            modelBuilder.Entity("SqlDisCache.Infrastrukture.Entity.TestCache", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(449)
                        .HasColumnType("nvarchar(449)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<DateTimeOffset?>("AbsoluteExpiration")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("SlidingExpirationInSeconds")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id")
                        .HasName("PK__DistributedCache__3214EC078136E5C6");

                    b.HasIndex(new[] { "ExpiresAtTime" }, "Index_ExpiresAtTime");

                    b.ToTable("DistributedCache", (string)null);
                });

            modelBuilder.Entity("CacheTagTestCache", b =>
                {
                    b.HasOne("SqlDisCache.Infrastrukture.Entity.TestCache", null)
                        .WithMany()
                        .HasForeignKey("CachItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlDisCache.Infrastrukture.Entity.CacheTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
